Use same log & response capture and upload for all BVT workflows
Signed-off-by: Matt Rutkowski <mrutkows@us.ibm.com>

diff --git a/.github/workflows/reusable-bvt-guardian-quantized-models-gguf.yml b/.github/workflows/reusable-bvt-guardian-quantized-models-gguf.yml
--- a/.github/workflows/reusable-bvt-guardian-quantized-models-gguf.yml
+++ b/.github/workflows/reusable-bvt-guardian-quantized-models-gguf.yml
@@ -40,8 +40,8 @@ env:
   EXT_GGUF: .gguf
   EXT_ENC: .enc
   FIND_ARGS: "-not -path '*/.*' -print | sed -e 's;[^/]*/;|___;g;s;___|; |;g'"
-  LLAMA_CLI_RESPONSE_FILE: response.txt
-  LLAMA_CLI_LOG_FILE: cli-log.txt
+  LLAMA_CLI_RESPONSE_FILE: .llama-cli.response.txt
+  LLAMA_CLI_LOG_FILE: .llama-cli.log.txt
   LLAMA_REQUEST_PROMPT_UNENCODED: test/prompts/granite/guardian/guardian_harm.txt
   LLAMA_REQUEST_TEMP: 0.0 # Note: MUST be zero (float)
   LLAMA_REQUEST_NUM_GPU_LAYERS: 0  # Note: in unknown "runners" we need to make sure GPU-spec. functions are not assumed.
@@ -113,6 +113,8 @@ jobs:
       run: |
         echo "TARGET_REPO_ID=${{inputs.target_repo_owner}}/${{env.REPO_NAME}}${{inputs.target_repo_name_ext}}" >> $GITHUB_ENV
         echo "BASE_FNAME_QUANTIZED_GGUF=${{ env.REPO_NAME }}-${{inputs.quantization}}${{env.EXT_GGUF}}" >> $GITHUB_ENV
+        echo "BASE_FNAME_LOG_FILE=${{env.REPO_NAME}}-${{inputs.quantization}}${{env.LLAMA_CLI_LOG_FILE}}" >> $GITHUB_ENV
+        echo "BASE_FNAME_RESPONSE_FILE=${{env.REPO_NAME}}-${{inputs.quantization}}${{env.LLAMA_CLI_RESPONSE_FILE}}" >> $GITHUB_ENV
 
     - name: set-derivative-env-vars-2
       run: |
@@ -124,6 +126,8 @@ jobs:
         echo "================== Derivative Environment Variables 1 =================="
         echo "TARGET_REPO_ID='$TARGET_REPO_ID' (${{ env.TARGET_REPO_ID }})"
         echo "BASE_FNAME_QUANTIZED_GGUF='$BASE_FNAME_QUANTIZED_GGUF' (${{ env.BASE_FNAME_QUANTIZED_GGUF }})"
+        echo "BASE_FNAME_LOG_FILE='$BASE_FNAME_LOG_FILE' (${{ env.BASE_FNAME_LOG_FILE }})"
+        echo "BASE_FNAME_RESPONSE_FILE='$BASE_FNAME_RESPONSE_FILE' (${{ env.BASE_FNAME_RESPONSE_FILE }})"
         echo "================== Derivative Environment Variables 2 =================="
         echo "LOCAL_MODEL_PATH='$LOCAL_MODEL_PATH' (${{ env.LOCAL_MODEL_PATH }})"
         echo "LOCAL_FNAME_QUANTIZED_GGUF='$LOCAL_FNAME_QUANTIZED_GGUF' (${{ env.LOCAL_FNAME_QUANTIZED_GGUF }})"
@@ -186,21 +190,27 @@ jobs:
           --n-gpu-layers ${{ env.LLAMA_REQUEST_NUM_GPU_LAYERS }} \
           --file ${{env.LLAMA_REQUEST_PROMPT_UNENCODED}}${{env.EXT_ENC}} 1> ${{env.LLAMA_RESPONSE_OUTPUT_FILE}}
         if [ $? -eq 1 ]; then
-          exit 1
+          echo "[ERROR] llama-cli failed:"
+          ls -al
+          echo "${{env.BASE_FNAME_LOG_FILE}}: '$(cat ${{env.BASE_FNAME_LOG_FILE}})'"
+          echo "${{env.BASE_FNAME_RESPONSE_FILE}}: '$(cat ${{env.BASE_FNAME_RESPONSE_FILE}})'"
+         exit 1
         fi
-        cat ${{env.LLAMA_RESPONSE_OUTPUT_FILE}}
-        cp ${{env.LLAMA_RESPONSE_OUTPUT_FILE}} ${{env.BASE_FNAME_QUANTIZED_GGUF}}-${{matrix.quantization}}.output.txt
+        echo "[SUCCESS] llama-cli succeeded:"
+        echo "${{env.BASE_FNAME_LOG_FILE}}: '$(cat ${{env.BASE_FNAME_LOG_FILE}})'"
+        echo "${{env.BASE_FNAME_RESPONSE_FILE}}: '$(cat ${{env.BASE_FNAME_RESPONSE_FILE}})'"
+        echo "${{env.BASE_FNAME_RESPONSE_FILE}} ($(wc -w ${{env.BASE_FNAME_RESPONSE_FILE}} | awk '{print $1}') words):\n'$(cat ${{env.LLAMA_CLI_RESPONSE_FILE}})'"
 
     - name: test-llama-cli-response-with-regex
       if: env.TEST_LLAMA_CLI == 'true'
       run: |
-        python ./scripts/test_regex_match_file.py "${{env.LLAMA_RESPONSE_REGEX}}" ${{env.LLAMA_RESPONSE_OUTPUT_FILE}}
+        python ./scripts/test_regex_match_file.py "${{env.LLAMA_RESPONSE_REGEX}}" ${{env.BASE_FNAME_RESPONSE_FILE}}
         echo "matched: '$matched'"
         if [[ "$exists" == "False" ]]; then
-          echo "[FAILURE] Regex `${{env.LLAMA_RESPONSE_REGEX}}` NOT matched in llama-llava-cli response."
+          echo "[FAILURE] Regex `${{env.LLAMA_RESPONSE_REGEX}}` NOT matched in llama-cli response."
           exit 1
         else
-          echo "[SUCCESS] Regex `${{env.LLAMA_RESPONSE_REGEX}}` matched in llama-llava-cli response."
+          echo "[SUCCESS] Regex `${{env.LLAMA_RESPONSE_REGEX}}` matched in llama-cli response."
         fi
 
     # See: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#upload-a-release-asset
