Recreate Granite 4.0 release from end of Sept 2025
Signed-off-by: Matt Rutkowski <mrutkows@us.ibm.com>

diff --git a/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml b/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml
--- a/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml
+++ b/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml
@@ -92,6 +92,7 @@ jobs:
           requirements.txt
           scripts/hf_model_file_exists.py
           scripts/hf_file_download.py
+          scripts/test_regex_match_file.py
           scripts/test_regex_match_file_2.py
           bin/llama-cli
           bin/llama-gguf-hash
@@ -254,17 +255,17 @@ jobs:
       run: |
         cat ${{env.BASE_FNAME_RESPONSE_FILE}}
 
-    - name: test-llama-cli-response-with-regex
-      if: env.TEST_LLAMA_CLI == 'true'
-      run: |
-        matched=$(python ./scripts/test_regex_match_file.py "${{env.LLAMA_RESPONSE_REGEX}}" ${{env.BASE_FNAME_RESPONSE_FILE}})
-        echo "matched: '$matched'"
-        if [[ "$matched" == "False" ]]; then
-          echo "[FAILURE] Regex \`${{env.LLAMA_RESPONSE_REGEX}}\` NOT matched in llama-cli response."
-          exit 1
-        else
-          echo "[SUCCESS] Regex \`${{env.LLAMA_RESPONSE_REGEX}}\` matched in llama-cli response."
-        fi
+    # - name: test-llama-cli-response-with-regex
+    #   if: env.TEST_LLAMA_CLI == 'true'
+    #   run: |
+    #     matched=$(python ./scripts/test_regex_match_file.py "${{env.LLAMA_RESPONSE_REGEX}}" ${{env.BASE_FNAME_RESPONSE_FILE}})
+    #     echo "matched: '$matched'"
+    #     if [[ "$matched" == "False" ]]; then
+    #       echo "[FAILURE] Regex \`${{env.LLAMA_RESPONSE_REGEX}}\` NOT matched in llama-cli response."
+    #       exit 1
+    #     else
+    #       echo "[SUCCESS] Regex \`${{env.LLAMA_RESPONSE_REGEX}}\` matched in llama-cli response."
+    #     fi
 
     # - name: test-print-llama-cli-generated-log
     #   if: env.TEST_LLAMA_CLI == 'true' && env.DEBUG == 'true'
