Add llama-llava-cli output testing
Signed-off-by: Matt Rutkowski <mrutkows@us.ibm.com>

diff --git a/.github/workflows/reusable-bvt-hf-llava-quantized-models-gguf.yml b/.github/workflows/reusable-bvt-hf-llava-quantized-models-gguf.yml
--- a/.github/workflows/reusable-bvt-hf-llava-quantized-models-gguf.yml
+++ b/.github/workflows/reusable-bvt-hf-llava-quantized-models-gguf.yml
@@ -165,43 +165,51 @@ jobs:
             --image ${{env.LLAMA_REQUEST_TEST_IMAGE}} \
             -c ${{env.LLAMA_REQUEST_CONTEXT_SIZE}} \
             -p "${{env.LLAMA_REQUEST_PROMPT_SYSTEM}}${{env.LLAMA_REQUEST_PROMPT_USER}}" \
-            --temp ${{env.LLAMA_REQUEST_TEMP}} 2> ${{env.LLAMA_CLI_STDERR_FILE}} | tee ${{env.LLAMA_CLI_STDOUT_FILE}}
+            --temp ${{env.LLAMA_REQUEST_TEMP}} 2> ${{env.LLAMA_CLI_STDERR_FILE}} 1> ${{env.LLAMA_CLI_STDOUT_FILE}}
         if [ $? -eq 1 ]; then
-          echo "failure"
+          echo "[ERROR] llama-llava-cli failed. Output (stderr):"
           cat ${{env.LLAMA_CLI_STDERR_FILE}}
           exit 1
         fi
-        echo "success"
+        echo "[SUCCESS] llama-llava-cli succeeded. Output (stdout):"
         cat ${{env.LLAMA_CLI_STDOUT_FILE}}
-        
-    - name: test-llama-llava-cli-2
-      timeout-minutes: 10
-      continue-on-error: true
-      run: |  
-        echo "invoking llama-llava-cli to test inference..."
-        echo "env.LOCAL_FNAME_MMPROJ_F16_GGUF=${{env.LOCAL_FNAME_MMPROJ_F16_GGUF}}"        
-        echo "env.LOCAL_FNAME_QUANTIZED_GGUF=${{env.LOCAL_FNAME_QUANTIZED_GGUF}}" 
-        ./bin/llama-llava-cli -m ${{env.LOCAL_FNAME_QUANTIZED_GGUF}} \
-            --mmproj ${{env.LOCAL_FNAME_MMPROJ_F16_GGUF}} \
-            --image ./test/images/cherry_blossom.jpg \
-            -c ${{env.LLAMA_REQUEST_CONTEXT_SIZE}} \
-            -p "${{env.LLAMA_REQUEST_PROMPT_SYSTEM}}${{env.LLAMA_REQUEST_PROMPT_USER}}" \
-            --temp ${{env.LLAMA_REQUEST_TEMP}} 2> ${{env.LLAMA_CLI_STDERR_FILE}} | tee ${{env.LLAMA_CLI_STDOUT_FILE}}          
 
-        if [ $? -eq 1 ]; then
-          echo "failure"
-          cat ${{env.LLAMA_CLI_STDERR_FILE}}
-          exit 1
-        fi
-        echo "success"
-        cat ${{env.LLAMA_CLI_STDOUT_FILE}}
+    # - name: test-llama-llava-cli-2
+    #   timeout-minutes: 10
+    #   continue-on-error: true
+    #   run: |  
+    #     echo "invoking llama-llava-cli to test inference..."
+    #     echo "env.LOCAL_FNAME_MMPROJ_F16_GGUF=${{env.LOCAL_FNAME_MMPROJ_F16_GGUF}}"        
+    #     echo "env.LOCAL_FNAME_QUANTIZED_GGUF=${{env.LOCAL_FNAME_QUANTIZED_GGUF}}" 
+    #     ./bin/llama-llava-cli -m ${{env.LOCAL_FNAME_QUANTIZED_GGUF}} \
+    #         --mmproj ${{env.LOCAL_FNAME_MMPROJ_F16_GGUF}} \
+    #         --image ./test/images/cherry_blossom.jpg \
+    #         -c ${{env.LLAMA_REQUEST_CONTEXT_SIZE}} \
+    #         -p "${{env.LLAMA_REQUEST_PROMPT_SYSTEM}}${{env.LLAMA_REQUEST_PROMPT_USER}}" \
+    #         --temp ${{env.LLAMA_REQUEST_TEMP}} 2> ${{env.LLAMA_CLI_STDERR_FILE}} 1> ${{env.LLAMA_CLI_STDOUT_FILE}}          
+
+    #     if [ $? -eq 1 ]; then
+    #       echo "[ERROR] llama-llava-cli failed. Output (stderr):"
+    #       cat ${{env.LLAMA_CLI_STDERR_FILE}}
+    #       exit 1
+    #     fi
+    #     echo "[SUCCESS] llama-llava-cli succeeded. Output (stdout):"
+    #     cat ${{env.LLAMA_CLI_STDOUT_FILE}}
 
     # - name: test-print-llama-cli-response-with-metrics
     #   if: env.TEST_LLAMA_CLI == 'true'      
     #   run: |
     #     echo "llama-cli: ${{env.LLAMA_CLI_RESPONSE_FILE}} ($(wc -w ${{env.LLAMA_CLI_RESPONSE_FILE}} | awk '{print $1}') words):\n'$(cat ${{env.LLAMA_CLI_RESPONSE_FILE}})'"
 
-    # - name: test-llama-cli-response-with-regex
-    #   if: env.TEST_LLAMA_CLI == 'true'      
-    #   run: |
-    #     python ./scripts/test_regex_match.py "${{env.LLAMA_RESPONSE_REGEX}}" "$(cat ${{env.LLAMA_CLI_RESPONSE_FILE}})"
+    - name: test-llama-cli-response-with-regex
+      if: env.TEST_LLAMA_CLI == 'true'      
+      run: |
+        matched = $(python ./scripts/test_regex_match.py "${{env.LLAMA_RESPONSE_REGEX}}" "$(cat ${{env.LLAMA_CLI_STDOUT_FILE}})")
+        echo "matched: $matched"
+        echo "exists: '$exists'"
+        if [[ "$exists" == "False" ]]; then
+          echo "[FAILURE] Regex `${{env.LLAMA_RESPONSE_REGEX}}` NOT matched in llama-llava-cli response." 
+          exit 1
+        else
+          echo "[SUCCESS] Regex `${{env.LLAMA_RESPONSE_REGEX}}` matched in llama-llava-cli response."
+        fi
