Improve BVT regex testing to allow percentage matching
Signed-off-by: Matt Rutkowski <mrutkows@us.ibm.com>

diff --git a/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml b/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml
--- a/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml
+++ b/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml
@@ -46,6 +46,7 @@ env:
   LLAMA_RUN_BIN: ./bin/llama-run # ./bin/llama-run
   LLAMA_RUN_FLAGS: "-v -n 9"
   LLAMA_RESPONSE_REGEX: "(Rayleigh|scatter)+"
+  LLAMA_RESPONSE_WORDS:  "Rayleigh,scatter,atmosphere"
   # LLAMA_RESPONSE_REGEX_2: "(Rayleigh|scatter)\s*(Rayleigh|scatter)" # allows spaces between
   LLAMA_SERVER_HOST: localhost
   LLAMA_SERVER_PORT: 8080
@@ -181,15 +182,15 @@ jobs:
     #     echo "--------------------"
     #     # ./bin/llama-gguf-hash --sha256 ~/Downloads/granite-3.0-1b-a400m-instruct-Q4_K_M.gguf > sha256.txt
 
-    - name: test-llama-server-with-quantized-gguf
-      if: env.TEST_LLAMA_SERVER == 'true'
-      timeout-minutes: 10
-      run: |
-        echo "--------------------"
-        echo "LOCAL_FNAME_QUANTIZED_GGUF='$LOCAL_FNAME_QUANTIZED_GGUF' (${{ env.LOCAL_FNAME_QUANTIZED_GGUF }})"
-        echo "--------------------"
-        echo "Starting llama-server on port ${{env.LLAMA_SERVER_PORT}}"
-        nohup ./bin/llama-server -m ./${{env.LOCAL_FNAME_QUANTIZED_GGUF}} --port ${{env.LLAMA_SERVER_PORT}} &
+    # - name: test-llama-server-with-quantized-gguf
+    #   if: env.TEST_LLAMA_SERVER == 'true'
+    #   timeout-minutes: 10
+    #   run: |
+    #     echo "--------------------"
+    #     echo "LOCAL_FNAME_QUANTIZED_GGUF='$LOCAL_FNAME_QUANTIZED_GGUF' (${{ env.LOCAL_FNAME_QUANTIZED_GGUF }})"
+    #     echo "--------------------"
+    #     echo "Starting llama-server on port ${{env.LLAMA_SERVER_PORT}}"
+    #     nohup ./bin/llama-server -m ./${{env.LOCAL_FNAME_QUANTIZED_GGUF}} --port ${{env.LLAMA_SERVER_PORT}} &
 
     # echo waiting for llama-server to start...
     # retry_count=0
@@ -206,36 +207,36 @@ jobs:
     #   fi
     # done
 
-    - name: test-llama-server-connection
-      if: env.TEST_LLAMA_SERVER == 'true'
-      run: |
-        echo "testing llama-server connection: ${{env.LLAMA_SERVER_HOST}}:${{env.LLAMA_SERVER_PORT}}..."
-        echo "netstat:\n$(netstat -an -p tcp | grep ".${{env.LLAMA_SERVER_HOST}}")"
+    # - name: test-llama-server-connection
+    #   if: env.TEST_LLAMA_SERVER == 'true'
+    #   run: |
+    #     echo "testing llama-server connection: ${{env.LLAMA_SERVER_HOST}}:${{env.LLAMA_SERVER_PORT}}..."
+    #     echo "netstat:\n$(netstat -an -p tcp | grep ".${{env.LLAMA_SERVER_HOST}}")"
 
-        if nc -v -z ${{env.LLAMA_SERVER_HOST}} ${{env.LLAMA_SERVER_PORT}}; then
-          echo "SUCCESS: Connection to llama-server successful."
-        else
-          echo "Failure: Connection to llama-server failed."
-          # ps aux
-          exit 1
-        fi
+    #     if nc -v -z ${{env.LLAMA_SERVER_HOST}} ${{env.LLAMA_SERVER_PORT}}; then
+    #       echo "SUCCESS: Connection to llama-server successful."
+    #     else
+    #       echo "Failure: Connection to llama-server failed."
+    #       # ps aux
+    #       exit 1
+    #     fi
 
-    - name: test-llama-server-with-curl
-      timeout-minutes: 5
-      if: env.TEST_LLAMA_SERVER == 'true'
-      run: |
-        curl --request GET --url http://${{env.LLAMA_SERVER_HOST}}:${{env.LLAMA_SERVER_PORT}}/health
-        echo "TODO: Test for {"status":"ok"} from GET /health"
-        echo "${{env.LLAMA_REQUEST_PROMPT}}"
-        curl --request POST \
-          --url ttp://${{env.LLAMA_SERVER_HOST}}:${{env.LLAMA_SERVER_PORT}}/completion \
-          --header "Content-Type: application/json" \
-          --data '{ \
-            "prompt": "${{env.LLAMA_REQUEST_PROMPT}}", \
-            "n_predict": ${{env.LLAMA_REQUEST_N_PREDICT}}, \
-            "seed": ${{env.LLAMA_REQUEST_SEED}} \
-          }'
-        echo "TODO: Test for JSON response from POST /completion endpoint using jq"
+    # - name: test-llama-server-with-curl
+    #   timeout-minutes: 5
+    #   if: env.TEST_LLAMA_SERVER == 'true'
+    #   run: |
+    #     curl --request GET --url http://${{env.LLAMA_SERVER_HOST}}:${{env.LLAMA_SERVER_PORT}}/health
+    #     echo "TODO: Test for {"status":"ok"} from GET /health"
+    #     echo "${{env.LLAMA_REQUEST_PROMPT}}"
+    #     curl --request POST \
+    #       --url ttp://${{env.LLAMA_SERVER_HOST}}:${{env.LLAMA_SERVER_PORT}}/completion \
+    #       --header "Content-Type: application/json" \
+    #       --data '{ \
+    #         "prompt": "${{env.LLAMA_REQUEST_PROMPT}}", \
+    #         "n_predict": ${{env.LLAMA_REQUEST_N_PREDICT}}, \
+    #         "seed": ${{env.LLAMA_REQUEST_SEED}} \
+    #       }'
+    #     echo "TODO: Test for JSON response from POST /completion endpoint using jq"
 
     # TODO:
     # - name: kill-llama-server
@@ -243,11 +244,11 @@ jobs:
     #   run: |
     #     echo "TODO: is netstat and ps commands to get PID and kill..."
 
+    # NOTE: if we want to ignore stderr use: 2>/dev/null
     - name: test-llama-cli
       if: env.TEST_LLAMA_CLI == 'true'
       timeout-minutes: 10
       continue-on-error: false
-      # 2>/dev/null
       run: |
         echo "invoking llama-cli to test inference (generation)..."
         echo "env.LOCAL_FNAME_QUANTIZED_GGUF=${{env.LOCAL_FNAME_QUANTIZED_GGUF}}"
@@ -255,7 +256,9 @@ jobs:
           -s ${{env.LLAMA_REQUEST_SEED}} \
           -m ./${{env.LOCAL_FNAME_QUANTIZED_GGUF}} \
           -p '${{env.LLAMA_REQUEST_PROMPT}}' \
-          -n ${{env.LLAMA_REQUEST_N_PREDICT}} --log-file ${{env.LLAMA_CLI_LOG_FILE}} 1>${{env.LLAMA_CLI_RESPONSE_FILE}}
+          -n ${{env.LLAMA_REQUEST_N_PREDICT}} \
+          --temp 0 \
+          --log-file ${{env.LLAMA_CLI_LOG_FILE}} 1>${{env.LLAMA_CLI_RESPONSE_FILE}}
         if [ $? -eq 1 ]; then
           echo "llama-cli: ${{env.LLAMA_CLI_RESPONSE_FILE}} ($(wc -w ${{env.LLAMA_CLI_RESPONSE_FILE}} | awk '{print $1}') words):\n'$(cat ${{env.LLAMA_CLI_RESPONSE_FILE}})'"
           exit 1
@@ -272,10 +275,10 @@ jobs:
         python ./scripts/test_regex_match_file.py "${{env.LLAMA_RESPONSE_REGEX}}" ${{env.LLAMA_CLI_RESPONSE_FILE}}
         echo "matched: '$matched'"
         if [[ "$exists" == "False" ]]; then
-          echo "[FAILURE] Regex '${{env.LLAMA_RESPONSE_REGEX}}' NOT matched in llama-llava-cli response."
+          echo "[FAILURE] Regex '${{env.LLAMA_RESPONSE_REGEX}}' NOT matched in llama-cli response."
           exit 1
         else
-          echo "[SUCCESS] Regex '${{env.LLAMA_RESPONSE_REGEX}}' matched in llama-llava-cli response."
+          echo "[SUCCESS] Regex '${{env.LLAMA_RESPONSE_REGEX}}' matched in llama-cli response."
         fi
 
     - name: test-print-llama-cli-generated-log
@@ -284,13 +287,25 @@ jobs:
       run: |
         echo "llama-cli: ${{env.LLAMA_CLI_LOG_FILE}}: '$(cat ${{env.LLAMA_CLI_LOG_FILE}})'"
 
-    - name: test-llama-run
-      if: env.TEST_LLAMA_RUN == 'true'
-      timeout-minutes: 10
-      continue-on-error: true
+    - name: test-llama-cli-response-with-regex-2
+      if: env.TEST_LLAMA_CLI == 'true'
       run: |
-        echo "invoking llama-run to test inference..."
-        ${{env.LLAMA_RUN_BIN}} ./${{env.LOCAL_FNAME_QUANTIZED_GGUF}} -p ${{env.LLAMA_REQUEST_PROMPT}} ${{env.LLAMA_RUN_FLAGS}}
-        if [ $? -eq 1 ]; then
+        python ./scripts/test_regex_match_file_2.py "${{env.LLAMA_CLI_RESPONSE_FILE}}" "${{env.LLAMA_RESPONSE_WORDS}}"
+        echo "matched: '$matched'"
+        if [[ "$exists" == "False" ]]; then
+          echo "[FAILURE] Regex '${{env.LLAMA_RESPONSE_REGEX}}' NOT matched in llama-cli response."
           exit 1
+        else
+          echo "[SUCCESS] Regex '${{env.LLAMA_RESPONSE_REGEX}}' matched in llama-cli response."
         fi
+
+    # - name: test-llama-run
+    #   if: env.TEST_LLAMA_RUN == 'true'
+    #   timeout-minutes: 10
+    #   continue-on-error: true
+    #   run: |
+    #     echo "invoking llama-run to test inference..."
+    #     ${{env.LLAMA_RUN_BIN}} ./${{env.LOCAL_FNAME_QUANTIZED_GGUF}} -p ${{env.LLAMA_REQUEST_PROMPT}} ${{env.LLAMA_RUN_FLAGS}}
+    #     if [ $? -eq 1 ]; then
+    #       exit 1
+    #     fi
