Support BVT of quantized vision GGUFs
Signed-off-by: Matt Rutkowski <mrutkows@us.ibm.com>

diff --git a/.github/workflows/reusable-convert-hf-to-f16-gguf.yml b/.github/workflows/reusable-convert-hf-to-f16-gguf.yml
--- a/.github/workflows/reusable-convert-hf-to-f16-gguf.yml
+++ b/.github/workflows/reusable-convert-hf-to-f16-gguf.yml
@@ -52,15 +52,21 @@ jobs:
     runs-on: macos-latest    
     steps:
     - uses: actions/checkout@v4
-    
+
     - name: Dump GitHub inputs
       env:
         GITHUB_INPUTS: ${{ toJson(inputs) }}
+        printenv | sort
       run: echo "$GITHUB_INPUTS"    
 
     - name: is-enable_llm_jobs
-      if: inputs.enable_llm_jobs == 'false'
+      # if: inputs.enable_llm_jobs == 'false'
       run: |
+        echo "exists: '$exists'"
+        if [[ "$exists" == "False" ]]; then
+          echo "FAILURE: model file: '${{env.TARGET_REPO_ID}}/${{env.BASE_FNAME_QUANTIZED_GGUF}}' does not exist."
+          exit 2
+        else 
         echo "inputs.enable_llm_jobs == 'false'. Exiting..."
         exit 0
 
