Add BVT for docker models
Signed-off-by: Matt Rutkowski <mrutkows@us.ibm.com>

diff --git a/.github/workflows/reusable-docker-package-push-model.yml b/.github/workflows/reusable-docker-package-push-model.yml
--- a/.github/workflows/reusable-docker-package-push-model.yml
+++ b/.github/workflows/reusable-docker-package-push-model.yml
@@ -279,28 +279,28 @@ jobs:
           ./model-cli package --gguf "${{env.ABSOLUTE_PATH_FNAME_QUANTIZED}}" ${{inputs.target_dockerhub_namespace}}/${{inputs.target_dockerhub_repository}}:${{env.TAG_LATEST}} --license "${{env.ABSOLUTE_PATH_FNAME_QUANTIZED}}" --push
           exit 0
 
-      - name: model pull
-        continue-on-error: true
-        run: |
-          cd model-runner/cmd/cli
-          ./model-cli status
-          echo "downloading model: ibmcom/yyz:foo ..."
-          ./model-cli pull ibmcom/yyz:foo
-          ./model-cli list
-          # echo "downloading model: ibmcom/granite4-test-2:foo ..."
-          # ./model-cli pull ibmcom/granite4-test-2:foo
-          # ./model-cli list
-          # echo "downloading model: ibmcom/granite4-test-2:8B-Q4_K_M ..."
-          ./model-cli pull ibmcom/granite4-test-2:8B-Q4_K_M --ignore-runtime-memory-check
-          pull_status=$?
-          echo "pull_status=$pull_status" >> $GITHUB_OUTPUT
-          if [ "$pull_status" -eq 0 ]; then
-            echo "[SUCCESS]: pulling 'ibmcom/granite4-test-2:8B-Q4_K_M'"
-            ./model-cli list
-          else
-            echo "[FAILURE]: pulling 'ibmcom/granite4-test-2:8B-Q4_K_M', exit code: '$pull_status'"
-            ./model-cli logs
-          fi
+      # - name: model pull
+      #   continue-on-error: true
+      #   run: |
+      #     cd model-runner/cmd/cli
+      #     ./model-cli status
+      #     echo "downloading model: ibmcom/yyz:foo ..."
+      #     ./model-cli pull ibmcom/yyz:foo
+      #     ./model-cli list
+      #     # echo "downloading model: ibmcom/granite4-test-2:foo ..."
+      #     # ./model-cli pull ibmcom/granite4-test-2:foo
+      #     # ./model-cli list
+      #     # echo "downloading model: ibmcom/granite4-test-2:8B-Q4_K_M ..."
+      #     # ./model-cli pull ibmcom/granite4-test-2:8B-Q4_K_M --ignore-runtime-memory-check
+      #     # pull_status=$?
+      #     # echo "pull_status=$pull_status" >> $GITHUB_OUTPUT
+      #     # if [ "$pull_status" -eq 0 ]; then
+      #     #   echo "[SUCCESS]: pulling 'ibmcom/granite4-test-2:8B-Q4_K_M'"
+      #     #   ./model-cli list
+      #     # else
+      #     #   echo "[FAILURE]: pulling 'ibmcom/granite4-test-2:8B-Q4_K_M', exit code: '$pull_status'"
+      #     #   ./model-cli logs
+      #     # fi
 
       - name: docker logs
         run: |
