Add repeat-penalty param. to llama-mtmd-cli for bvt
Signed-off-by: Matt Rutkowski <mrutkows@us.ibm.com>

diff --git a/.github/workflows/reusable-bvt-docling-quantized-models-gguf.yml b/.github/workflows/reusable-bvt-docling-quantized-models-gguf.yml
--- a/.github/workflows/reusable-bvt-docling-quantized-models-gguf.yml
+++ b/.github/workflows/reusable-bvt-docling-quantized-models-gguf.yml
@@ -60,7 +60,8 @@ env:
   TEST_LLAMA_CLI: true
   TEST_LLAMA_RUN: false
   F16_MMPROJ_MODEL_BASE_FILENAME: mmproj-model
-  LLAMA_REQUEST_TEST_IMAGE: "test/images/sample-text-screenshot.png"
+  LLAMA_REQUEST_TEST_IMAGE_1: "test/images/sample-text-screenshot.png"
+  LLAMA_REQUEST_TEST_IMAGE_2: "test/images/old_newspaper.png"
   LLAMA_REQUEST_TEMP: 0
   LLAMA_REQUEST_CONTEXT_SIZE: 16384
   LLAMA_CLI_REPEAT_PENALTY: 1.05
@@ -187,8 +188,7 @@ jobs:
       run: |
         ./bin/llama-mtmd-cli --help
 
-    # --temp ${{env.LLAMA_REQUEST_TEMP}}
-    - name: test-llama-mtmd-cli
+    - name: test-llama-mtmd-cli-1
       timeout-minutes: 10
       continue-on-error: true
       run: |
@@ -198,7 +198,35 @@ jobs:
         echo "env.LOCAL_FNAME_QUANTIZED_GGUF=${{env.LOCAL_FNAME_QUANTIZED_GGUF}}"
         ./bin/llama-mtmd-cli  -m ${{env.LOCAL_FNAME_QUANTIZED_GGUF}} \
             --mmproj ${{env.LOCAL_FNAME_MMPROJ_BF16_GGUF}} \
-            --image ${{env.LLAMA_REQUEST_TEST_IMAGE}} \
+            --image ${{env.LLAMA_REQUEST_TEST_IMAGE_1}} \
+            -p "${{env.LLAMA_REQUEST_PROMPT_USER}}" \
+            --temp ${{env.LLAMA_REQUEST_TEMP}} \
+            --repeat-penalty ${{env.LLAMA_CLI_REPEAT_PENALTY}} \
+            --verbose \
+            -ngl 99 2> ${{env.LLAMA_CLI_STDERR_FILE}} 1> ${{env.LLAMA_CLI_STDOUT_FILE}}
+        if [ $? -eq 1 ]; then
+          echo "[ERROR] llama-mtmd-cli failed. Output (stderr):"
+          ls -al
+          cat ${{env.LLAMA_CLI_STDERR_FILE}}
+          cat ${{env.LLAMA_CLI_STDOUT_FILE}}
+          exit 1
+        fi
+        echo "[SUCCESS] llama-mtmd-cli succeeded. Output (stdout):"
+        ls -al
+        cat ${{env.LLAMA_CLI_STDERR_FILE}}
+        cat ${{env.LLAMA_CLI_STDOUT_FILE}}
+
+    - name: test-llama-mtmd-cli-2
+      timeout-minutes: 10
+      continue-on-error: true
+      run: |
+        echo "invoking llama-mtmd-cli to test inference..."
+        echo "env.LOCAL_FNAME_MMPROJ_F16_GGUF=${{env.LOCAL_FNAME_MMPROJ_F16_GGUF}}"
+        echo "env.LOCAL_FNAME_MMPROJ_BF16_GGUF=${{env.LOCAL_FNAME_MMPROJ_BF16_GGUF}}"
+        echo "env.LOCAL_FNAME_QUANTIZED_GGUF=${{env.LOCAL_FNAME_QUANTIZED_GGUF}}"
+        ./bin/llama-mtmd-cli  -m ${{env.LOCAL_FNAME_QUANTIZED_GGUF}} \
+            --mmproj ${{env.LOCAL_FNAME_MMPROJ_BF16_GGUF}} \
+            --image ${{env.LLAMA_REQUEST_TEST_IMAGE_2}} \
             -p "${{env.LLAMA_REQUEST_PROMPT_USER}}" \
             --temp ${{env.LLAMA_REQUEST_TEMP}} \
             --repeat-penalty ${{env.LLAMA_CLI_REPEAT_PENALTY}} \
