Improve BVT regex testing to allow percentage matching
Signed-off-by: Matt Rutkowski <mrutkows@us.ibm.com>

diff --git a/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml b/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml
--- a/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml
+++ b/.github/workflows/reusable-bvt-instruct-quantized-models-gguf.yml
@@ -115,6 +115,7 @@ jobs:
       run: |
         echo "TARGET_REPO_ID=${{inputs.target_repo_owner}}/${{env.REPO_NAME}}${{inputs.target_repo_name_ext}}" >> $GITHUB_ENV
         echo "BASE_FNAME_QUANTIZED_GGUF=${{ env.REPO_NAME }}-${{inputs.quantization}}${{env.EXT_GGUF}}" >> $GITHUB_ENV
+        echo "BASE_FNAME_LOG_FILE=${{ env.REPO_NAME }}-${{inputs.quantization}}-${{env.LLAMA_CLI_LOG_FILE}}" >> $GITHUB_ENV
 
     - name: set-derivative-env-vars-2
       run: |
@@ -129,6 +130,7 @@ jobs:
         echo "================== Derivative Environment Variables 1 =================="
         echo "TARGET_REPO_ID='$TARGET_REPO_ID' (${{ env.TARGET_REPO_ID }})"
         echo "BASE_FNAME_QUANTIZED_GGUF='$BASE_FNAME_QUANTIZED_GGUF' (${{ env.BASE_FNAME_QUANTIZED_GGUF }})"
+        echo "BASE_FNAME_LOG_FILE='$BASE_FNAME_LOG_FILE' (${{ env.BASE_FNAME_LOG_FILE }})"
         echo "================== Derivative Environment Variables 2 =================="
         echo "LOCAL_MODEL_PATH='$LOCAL_MODEL_PATH' (${{ env.LOCAL_MODEL_PATH }})"
         echo "================== Derivative Environment Variables 3 =================="
@@ -258,66 +260,63 @@ jobs:
           -p '${{env.LLAMA_REQUEST_PROMPT}}' \
           -n ${{env.LLAMA_REQUEST_N_PREDICT}} \
           --temp 0 \
-          --log-file ${{env.LLAMA_CLI_LOG_FILE}} 1>${{env.LLAMA_CLI_RESPONSE_FILE}}
+          --log-file ${{env.BASE_FNAME_LOG_FILE}} 1>${{env.LLAMA_CLI_RESPONSE_FILE}}
         if [ $? -eq 1 ]; then
+          echo "llama-cli: ${{env.BASE_FNAME_LOG_FILE}}: '$(cat ${{env.BASE_FNAME_LOG_FILE}})'"
           echo "llama-cli: ${{env.LLAMA_CLI_RESPONSE_FILE}} ($(wc -w ${{env.LLAMA_CLI_RESPONSE_FILE}} | awk '{print $1}') words):\n'$(cat ${{env.LLAMA_CLI_RESPONSE_FILE}})'"
           exit 1
-        fi
-
-    - name: test-print-llama-cli-response-with-metrics
-      if: env.TEST_LLAMA_CLI == 'true'
-      run: |
-        echo "llama-cli: ${{env.LLAMA_CLI_RESPONSE_FILE}} ($(wc -w ${{env.LLAMA_CLI_RESPONSE_FILE}} | awk '{print $1}') words):\n'$(cat ${{env.LLAMA_CLI_RESPONSE_FILE}})'"
-
-    - name: test-llama-cli-response-with-regex
-      if: env.TEST_LLAMA_CLI == 'true'
-      run: |
-        python ./scripts/test_regex_match_file.py "${{env.LLAMA_RESPONSE_REGEX}}" ${{env.LLAMA_CLI_RESPONSE_FILE}}
-        echo "matched: '$matched'"
-        if [[ "$exists" == "False" ]]; then
-          echo "[FAILURE] Regex '${{env.LLAMA_RESPONSE_REGEX}}' NOT matched in llama-cli response."
-          exit 1
-        else
-          echo "[SUCCESS] Regex '${{env.LLAMA_RESPONSE_REGEX}}' matched in llama-cli response."
         fi
 
     - name: test-print-llama-cli-generated-log
       if: env.TEST_LLAMA_CLI == 'true' && env.DEBUG == 'true'
       continue-on-error: true
       run: |
-        echo "llama-cli: ${{env.LLAMA_CLI_LOG_FILE}}: '$(cat ${{env.LLAMA_CLI_LOG_FILE}})'"
+        echo "llama-cli: ${{env.BASE_FNAME_LOG_FILE}}: '$(cat ${{env.BASE_FNAME_LOG_FILE}})'"
 
-    - name: test-llama-cli-response-with-regex-2
+    - name: test-print-llama-cli-response-with-metrics
       if: env.TEST_LLAMA_CLI == 'true'
       run: |
-        python ./scripts/test_regex_match_file_2.py "${{env.LLAMA_CLI_RESPONSE_FILE}}" "${{env.LLAMA_RESPONSE_WORDS}}"
-        echo "matched: '$matched'"
-        if [[ "$exists" == "False" ]]; then
-          echo "[FAILURE] Regex '${{env.LLAMA_RESPONSE_REGEX}}' NOT matched in llama-cli response."
-          exit 1
-        else
-          echo "[SUCCESS] Regex '${{env.LLAMA_RESPONSE_REGEX}}' matched in llama-cli response."
-        fi
+        echo "llama-cli: ${{env.LLAMA_CLI_RESPONSE_FILE}} ($(wc -w ${{env.LLAMA_CLI_RESPONSE_FILE}} | awk '{print $1}') words):\n'$(cat ${{env.LLAMA_CLI_RESPONSE_FILE}})'"
+
+    # - name: test-llama-cli-response-with-regex
+    #   if: env.TEST_LLAMA_CLI == 'true'
+    #   run: |
+    #     python ./scripts/test_regex_match_file.py "${{env.LLAMA_RESPONSE_REGEX}}" ${{env.LLAMA_CLI_RESPONSE_FILE}}
+    #     echo "matched: '$matched'"
+    #     if [[ "$exists" == "False" ]]; then
+    #       echo "[FAILURE] Regex '${{env.LLAMA_RESPONSE_REGEX}}' NOT matched in llama-cli response."
+    #       exit 1
+    #     else
+    #       echo "[SUCCESS] Regex '${{env.LLAMA_RESPONSE_REGEX}}' matched in llama-cli response."
+    #     fi
+
+    # - name: test-llama-cli-response-with-regex-2
+    #   if: env.TEST_LLAMA_CLI == 'true'
+    #   run: |
+    #     python ./scripts/test_regex_match_file_2.py "${{env.LLAMA_CLI_RESPONSE_FILE}}" "${{env.LLAMA_RESPONSE_WORDS}}"
+    #     echo "matched: '$matched'"
+    #     if [[ "$exists" == "False" ]]; then
+    #       echo "[FAILURE] Regex '${{env.LLAMA_RESPONSE_REGEX}}' NOT matched in llama-cli response."
+    #       exit 1
+    #     else
+    #       echo "[SUCCESS] Regex '${{env.LLAMA_RESPONSE_REGEX}}' matched in llama-cli response."
+    #     fi
 
     - name: test-llama-cli-response-with-regex-3
       if: env.TEST_LLAMA_CLI == 'true'
       run: |
         python_output=$(python ./scripts/test_regex_match_file_2.py "${{env.LLAMA_CLI_RESPONSE_FILE}}" "${{env.LLAMA_RESPONSE_WORDS}}")
+        # echo "Full Python Output:"
+        # echo "$python_output"
 
         # Extract the last line of the output, which contains "true" or "false"
         return_value=$(echo "$python_output" | tail -n 1)
 
-        # Print the captured output for verification
-        echo "Full Python Output:"
-        echo "$python_output"
-
-        echo "Extracted Return Value: $return_value"
-
         # Use the extracted "boolean" string in a conditional
         if [ "$return_value" = "true" ]; then
-            echo "Python script returned true."
+          echo "[SUCCESS]"
         else
-            echo "Python script returned false."
+          echo "[FAILURE]"
         fi
 
     # - name: test-llama-run
