Develop workflow to test quantized GGUF models
Signed-off-by: Matt Rutkowski <mrutkows@us.ibm.com>

diff --git a/.github/workflows/test-quantized-models-gguf.yml b/.github/workflows/test-quantized-models-gguf.yml
--- a/.github/workflows/test-quantized-models-gguf.yml
+++ b/.github/workflows/test-quantized-models-gguf.yml
@@ -29,7 +29,7 @@ env:
   TARGET_REPO_NAME_EXT: -GGUF
   TARGET_REPO_OWNER: mrutkows # ibm-research
   DEBUG: true
-  LLAMA_SERVER_PORT: 8080
+  LLAMA_SERVER_PORT: 6666
   LLAMA_SERVER_LOCALHOST: "http://127.0.0.1"
   QUANTIZED_MODEL_EXISTS: false
   LLAMA_CLI_OUTPUT_FILE: response.txt
@@ -194,11 +194,11 @@ jobs:
         echo "LOCAL_FNAME_QUANTIZED_GGUF='$LOCAL_FNAME_QUANTIZED_GGUF' (${{ env.LOCAL_FNAME_QUANTIZED_GGUF }})"          
         echo "--------------------"    
         echo "Starting llama-server on port ${{env.LLAMA_SERVER_PORT}}"      
-        nohup ./bin/llama-server -m ./${{env.LOCAL_FNAME_QUANTIZED_GGUF}} --port ${{env.LLAMA_SERVER_PORT}} &
-        echo waiting for llama-server to start...        
+        nohup ./bin/llama-server -m ./${{env.LOCAL_FNAME_QUANTIZED_GGUF}} --port ${{env.LLAMA_SERVER_PORT}} &      
 
     - name: test-inference-against-llama-server
       run: |
+        echo waiting for llama-server to start...  
         retry_count=0
         max_retries=10
         while ! nc -v -z localhost ${{env.LLAMA_SERVER_PORT}} && [ $retry_count -lt $max_retries ]; do
@@ -213,9 +213,14 @@ jobs:
             retry_count=$((retry_count + 1)) 
           fi          
         done    
-
-        echo "invoking llama-cli to test inference against llama-server..."
-        ./bin/llama-cli --log-disable -s 647063347 -m ./${{env.LOCAL_FNAME_QUANTIZED_GGUF}} -p "What color is the sky?" -no-cnv -n 128 --log-file generated-log.txt 2>/dev/null 1>response.txt
+        if [ $? -eq 0 ]; then
+          echo "Connection successful!"
+          echo "invoking llama-cli to test inference against llama-server..."
+          ./bin/llama-cli --log-disable -s 647063347 -m ./${{env.LOCAL_FNAME_QUANTIZED_GGUF}} -p "What color is the sky?" -no-cnv -n 128 --log-file generated-log.txt 2>/dev/null 1>response.txt
+        else
+          echo "Connection failed"
+          exit 1
+        fi  
 
     - name: print-response-metrics
       run: |
