Develop workflow to test quantized GGUF models
Signed-off-by: Matt Rutkowski <mrutkows@us.ibm.com>

diff --git a/.github/workflows/test-quantized-models-gguf.yml b/.github/workflows/test-quantized-models-gguf.yml
--- a/.github/workflows/test-quantized-models-gguf.yml
+++ b/.github/workflows/test-quantized-models-gguf.yml
@@ -202,17 +202,22 @@ jobs:
         retry_count=0
         max_retries=10
         while ! nc -v -z localhost ${{env.LLAMA_SERVER_PORT}} && [ $retry_count -lt $max_retries ]; do
-          echo $?
-          echo "sleeping 1 second..."  && sleep 1
+          echo $retry_count
+          echo "sleeping 1 second..." && sleep 1
+          if [ $? -eq 0 ]; then
+            echo "Connection successful!"
+            break
+          else
+            echo "Connection failed, retrying..."
+            echo "sleeping 1 second..." && sleep 1
+            retry_count=$((retry_count + 1)) 
+          fi          
         done    
-        echo $? 
+
         echo "invoking llama-cli to test inference against llama-server..."
         ./bin/llama-cli --log-disable -s 647063347 -m ./${{env.LOCAL_FNAME_QUANTIZED_GGUF}} -p "What color is the sky?" -no-cnv -n 128 --log-file generated-log.txt 2>/dev/null 1>response.txt
-        echo "llama-cli: response.txt:"
-        echo "-----"
-        cat response.txt
-        echo "-----"
-        echo "'$(cat response.txt)'"
+
     - name: print-response-metrics
       run: |
-        echo "word count: $(wc -m response.txt | awk '{print $1})'"
+        echo "llama-cli: response.txt: '$(cat response.txt)'"
+        echo "word count: $(wc -w response.txt)"
